[package]
name = "sp-ark-ed-on-bls12-381-bandersnatch"
version = "0.4.0-alpha"
authors = [ "zhenfei zhang", "arkworks contributors" ]
description = "Bandersnatch: a curve defined over the scalar field of the BLS12-381 curve"
repository = "https://github.com/zhenfeizhang/bandersnatch-rust"
keywords = ["cryptography", "finite-fields", "elliptic-curves" ]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
ark-ff = { version = "0.4.0", default-features = false }
ark-std = { version = "0.4.0", default-features = false }
ark-r1cs-std = { version = "0.4.0", default-features = false, optional = true }
sp-ark-bls12-381 = { version = "0.4.0-alpha", path = "../bls12_381", default-features = false, features = [ "scalar_field" ] }
sp-ark-models = { path = "../../models", version = "0.4.0-alpha", default-features = false }
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false }
ark-scale = { git = "https://github.com/w3f/ark-scale", version = "0.0.2", features = ["hazmat"], default-features = false }
ark-ed-on-bls12-381-bandersnatch = { version = "0.4.0", default-features = false }
sp-io =  { git = "https://github.com/paritytech/substrate.git", "branch" = "achimcc/arkworks-integration", version = "7.0.0",  default-features = false }
ark-ec = { version = "0.4.0", default-features = false }

[features]
default = ["std"]
std = [
    "ark-ff/std",
    "ark-std/std",
    "ark-r1cs-std/std",
    "sp-ark-bls12-381/std",
    "sp-ark-models/std", 
    "codec/std",
    "ark-scale/std",
    "ark-ed-on-bls12-381-bandersnatch/std",
    "sp-io/std", 
]
r1cs = ["ark-r1cs-std"]
