name: Run benchmarks

on:
  push:
    branches:    
      - '*'
  pull_request:
    branches: 

  workflow_dispatch:

jobs:   
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
      - name: Install protoc
        uses: taiki-e/install-action@v1
        with:
          tool: protoc
      - name: clone substrate-arkworks-examples for benchmarking
        run: git clone https://github.com/achimcc/substrate-arkworks-examples
      - name: ls
        run: cd /home/runner/work && ls -la
      - name: Compute benchmarks for main branch
        run: |
          cd substrate-arkworks-examples && \
          cargo +nightly bench  \
          -p sp-ark-bls12-381 \
          sp-ark-bls12-377 \
          sp-ark-bw6-761 \
          sp-ark-ed-on-bls12-377 \
          sp-ark-ed-on-bls12-381 \
          | tee ../results-main.txt
      - name: clone repo
        run: git clone https://github.com/paritytech/ark-substrate
      - name: Get patched Cargo.toml
        run: cp ark-substrate/benchmarking/Cargo.toml substrate-arkworks-examples/Cargo.toml
      - name: Use current PR branch for benchmarking
        run: sed -i 's,replace-with-pr-branch,${{ github.ref_name }},g' substrate-arkworks-examples/Cargo.toml
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6   
      - name: Running on the default branch.
        if: steps.branch-name.outputs.is_default == 'true'
        run: |
          echo "Running on default: ${{ steps.branch-name.outputs.current_branch }}"
      - name: Running on a pull request branch.
        if: steps.branch-name.outputs.is_default == 'false'
        run: |
          echo "Running on pr: ${{ steps.branch-name.outputs.current_branch }}"
      - name: Compute benchmarks for pr branch
        run: |
          cd substrate-arkworks-examples && \
          cargo +nightly bench  \
          -p sp-ark-bls12-381 \
          sp-ark-bls12-377 \
          sp-ark-bw6-761 \
          sp-ark-ed-on-bls12-377 \
          sp-ark-ed-on-bls12-381 \
          | tee ../results-pr.txt
      - name: Compare benchmark result
        uses: openpgpjs/github-action-pull-request-benchmark@v1
        with:
          name: Time benchmark
          tool: cargo
          pr-benchmark-file-path: results-main.txt
          base-benchmark-file-path: results-pr.txt
          comment-on-alert: true
          alert-threshold: 130%
          fail-on-alert: true
          fail-threshold: 150%
          github-token: ${{ secrets.GITHUB_TOKEN }}
  
         
  
         