name: Run benchmarks

on:
  push:
    branches:    
      - '*'
  pull_request:
    branches: 

  workflow_dispatch:

jobs:   
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
      - name: Install protoc
        uses: taiki-e/install-action@v1
        with:
          tool: protoc
      - name: clone substrate-arkworks-examples for benchmarking
        run: git clone https://github.com/achimcc/substrate-arkworks-examples
      - name: ls
        run: cd /home/runner/work && ls -la
      - name: Compute benchmarks for main branch
        run: |
          cd substrate-arkworks-examples && \
          cargo +nightly bench pallet-template \
          -- --json > ../results-main.json
      - name: clone repo
        run: git clone https://github.com/paritytech/ark-substrate
      - name: Get patched Cargo.toml
        run: cp ark-substrate/benchmarking/Cargo.toml substrate-arkworks-examples/Cargo.toml
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6  
      - name: Use current PR branch for benchmarking
        run: sed -i 's,replace-with-pr-branch,{{ steps.branch-name.outputs.current_branch }},g' substrate-arkworks-examples/Cargo.toml 
      - name: Compute benchmarks for pr branch
        run: |
          cd substrate-arkworks-examples && \
          cargo +nightly bench pallet-template \
          -- --json > ../results-pr.json
      - name: cat pr
        run: cat results-pr.txt
      - name: cat main
        run: cat results-main.txt
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'cargo'
          output-file-path: results-main.json
          external-data-json-path: results-pr.json
          fail-on-alert: true
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable alert commit comment
          comment-on-alert: true
          # Mention @rhysd in the commit comment
          alert-comment-cc-users: '@achimcc'
  
         
  
         