name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-D warnings'
  RUST_BACKTRACE: 1

jobs:   
  rustfmt:
    name: Rust format
    runs-on: ubuntu-latest
    steps:
      - name: install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      - name: checkout repo
        uses: actions/checkout@v4
      - name: cargo format
        run: cargo fmt --all -- --check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Check Build
        run: |
          cargo build --workspace --release

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt      
      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          toolchain: stable
          command: clippy
          args: --workspace --all-targets

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Run tests
        run: cargo test --workspace --verbose --release
